version: '3.2'
services:
    coredns:
        image: coredns/coredns
        container_name: tmax-coredns
        restart: always # other option: always - if you want persistent through host reboots
        expose:
            - "53"
            - "53/udp"
        ports:
            - "53:53"
            - "53:53/udp"
        volumes:
            - type : "bind"
              source : "${PWD}/config"
              target : "/etc/coredns"
        entrypoint:
            - "/coredns"
            - "-dns.port=53"
            - "-conf=/etc/coredns/Corefile"
